name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git clone https://github.com/planetfederal/qgis-testing-environment-docker qgis-docker
        cd qgis-docker
        docker build -t qgis-testing-environment \
          --build-arg QGIS_REPOSITORY='https://github.com/qgis/QGIS.git' \
          --build-arg QGIS_BRANCH='master' \
          --build-arg LEGACY='false'
